# -*- coding: utf-8 -*-
from utils.compression import encode

input_string = "LlllLyIiiFFFFFfFAaACCccCCCCcEEeeeXJjJjJjJzZZzaAaAaaAAAeeeEEEEEHHHHhHHHmZZzZzZZzztttTTTtAaAaAaiiinNNNNNNNDDdddDYYyYqQQaAAAAzzUuuUUuUUuFfFfJJJJJJJJjqtTttTtTCccCCCCCLlllLlLLLlLllLlttTTtTttuuuUuUqQrYYYyYyYyyWwwwgGGgGGHhkkKkKKlFfffFffFfWwWwWWWkkKkkKbBGgggGGGNNWwWwwWuUUuuuuaaAaAAGgMmmhhHHbBGgGgGgGgGgGGGGgAATtttKKKkKKZaAAaYYyyZzzpppUuiiIiiiIIiMMMmmssSSSssSsgggGgJxxXXTTAaeeeeekKkKKKkKVVvBbbBBBBBVXWwWWmmMmMmMMMjJjAAAAaKKkoOooooOpPBbbbBbBbbbbBkkKKKKKfeEeEeEhhhHHHeeeehhIiIIzzZZzzzvvVVtttTTtPPppPPPpPPPppXXXXxxtmMmmMmMmyyyyyyyzZPmmMmMmmojjjjjJJkKkkknnyYYYYyYAAkKKkkpPPPKkKQqqQqqwWWWWWwWOOoOOOOOOeeEEExxxxXiiIIbBbbBdDdJYyyyYyYZZzZZEnNrRrraAAaaaWLLlLljJzzzzZEEeeEEEEeHhhhDddDDDllLJbaAaAAAaAeuuuUUuUuvVVvVmMmMmmMhhhHhHwwWWwWPpPpPqqPpPPPPpPiiIUuuUuUAaAaWfffffFFFFVVVvVvVvvoOoooOZZKkkKkkkWWwWwWzZzzZAaAAaAgGggGGGGXXxxxxxXvxXxXxpPpPppPpHhHHjjjJjJjrrrrRrrRaAAAaaaJjJjukKKrrRRRRrRaaAAaaabbHhhhhhaavvfFfFfFQqqQeTTTTttttbBbbbBMMMmMmMMmzZzZzeeeEEEEeyYYYyyafNnnnnnnzZzeEeEEhHHhhhHmMmmMmAaaaLLllLLllaaOeeEeEUUuUUuUuGggrvvTTtttMMMmMmmtTTttTttTsSSSSSSS"

print "\nString original\n"
print input_string
print "\nString codificado\n"
print encode(input_string)
print "\n"
